### ISSUE TITLE
/init: 45: exec: s6-overlay-suexec: not found

### ISSUE THREAD

**Issue by Mogelschrift** [meeb/tubesync#1018]
Hello, i get the following error since today. I am unable to get the container running, even if i wipe all config data and database.

> tubesync  | 2025-05-05T10:12:51.981142682Z /init: 45: exec: s6-overlay-suexec: not found
tubesync  | 2025-05-05T10:12:52.605061125Z /init: 45: exec: s6-overlay-suexec: not found

**Comment by Mogelschrift** [comment]
I used `latest `and `v0.13.7`, both dont work. The container worked perfectly fine before i restarted my server. All other docker container work too.

**Comment by tcely** [comment]
There must be something about your configuration causing this.

```
$ stat /command/s6-overlay-suexec ; realpath -e /command/s6-overlay-suexec
File: /command/s6-overlay-suexec -> ../package/admin/s6-overlay-helpers/command/s6-overlay-suexec
Size: 61              Blocks: 8          IO Block: 4096   symbolic link
Device: 0,68    Inode: 187060      Links: 1
Access: (0777/lrwxrwxrwx)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2025-05-01 04:26:58.000000000 +0000
Modify: 2025-05-01 04:26:58.000000000 +0000
Change: 2025-05-05 06:02:33.383245764 +0000
Birth: 2025-05-05 06:02:33.383245764 +0000
/package/admin/s6-overlay-helpers-0.1.1.0/command/s6-overlay-suexec
```

We will need to know more about how you are starting the container and how it is configured to help.

**Comment by Mogelschrift** [comment]
Docker Compose
```yml
services:
  tubesync:
    image: ghcr.io/meeb/tubesync:latest
    container_name: tubesync
    restart: unless-stopped
    ports:
      - 4848:4848
    volumes:
      - /home/docker-user/tubesync-n:/config:rw
      - /movie/youtube/downloads:/downloads:rw
    environment:
      - TZ=Europe/Berlin
      - PUID=1001
      - PGID=996
``` 

Starting via Komodo
