### ISSUE TITLE
Stuck on "Updating metadata from indexing results" – tasks pile up, no further processing

### ISSUE THREAD

**Issue by tehKNi** [meeb/tubesync#1134]
**Describe the bug**
Since about a week ago (mid-June 2025), TubeSync started exhibiting an issue where indexing appears to complete normally, but then gets stuck on `Updating metadata from indexing results`. At this point, the relevant tasks never run, and new "updating metadata" tasks either pile up or block all further operations. Only a `reset-tasks` seems to temporarily restore activity, but the issue quickly returns.

**Environment**
* TubeSync: `0.15.6`
* yt-dlp: `2025.06.09`
* FFmpeg: `N-119898-ge6fb8f373e-20250616`
* PostgreSQL `15.2` (Docker)

**Docker Compose excerpt**
```yaml
tubesync:
  image: ghcr.io/meeb/tubesync:latest
  environment:
    - TUBESYNC_WORKERS=2
    - TUBESYNC_DEBUG=True
    - DATABASE_CONNECTION=postgresql://postgres:<password>@tubesync-db:5432/tubesync
  depends_on:
    - tubesync-db

tubesync-db:
  image: postgres:15.2
  environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=<password>
```

**To Reproduce**
1. Start indexing a source with many videos (playlist/channel)
2. Observe logs: items are fetched and indexed
3. See `Updating metadata from indexing results for: "<video_id>": <video_title>`
4. Task says "Task will run immediately", but it never runs
5. All subsequent tasks remain stuck in this state
6. Only a `reset-tasks` temporarily helps, but issue recurs immediately

**Logs**

```
[INFO] Found 121 media items for source: <source>
[DEBUG] Indexed media: 1: <source> / <video_id>
...
[DEBUG] Indexed media: 121: <source> / <video_id>
[INFO] Updating metadata from indexing results for: "<video_id>": <video_title>
Task will run immediately
```

No further log entries, and TubeSync appears "stuck" until forced reset even with debug logs set to True.

**What I tried**

* Restarted containers
* Ran `reset-tasks` (only temporary effect)
* Enabled debug mode (no new clues, logs simply stop)
* Observed: direct `Downloading metadata for: <video_id>` tasks *do* work, but all "updating metadata" tasks never run

**Additional notes**

* No database, config, or disk errors are reported
* Problem started recently after like a year of stable use
* Only affects "updating metadata" tasks afaik

**Request**
Any idea how to debug this further or what might have changed recently? Is there a way to clear out "stuck" updating tasks, or is something blocking the queue/thread?
