### ISSUE TITLE
Frequent 500 internal server errors (Failed to retrieve tasks. Database Unreachable.)

### ISSUE THREAD

**Issue by Casuallynoted** [meeb/tubesync#120]
I'm currently running tubesync via docker, accessing via the local IP and port. I've noticed that more often than not when I've refreshed a page or navigated to a different page, it throws a 500 internal server error. I can refresh and eventually it'll load, but it oftentimes takes several tries before it loads again. This issue does not happen when no sources have been added. After adding a source, it happens nonstop. I'm noticing a "Failed to retrieve tasks. Database Unreachable." in the console multiple times over.

**Comment by meeb** [comment]
Is it a large source with a load of videos? Are you using the SQLite default database? Where is the SQLite database stored? Locally, or on a network drive?

Basically write contention to the database is a common issue with large channels or if the database is stored on a network share, you can solve it by switching to a heavier backend like Postgres.

**Comment by Extarys** [comment]
I also started getting 500 errors. I updated to the latest version but it was still happening, hence my presence on GitHub :laughing: 

HDD is a WD black, attached directly to the computer (SATA3) running TubeSync.

I deleted the tubesync folder, restarted the container  and added a single source. Now when I try to edit that source while tubesync is indexing I get 500 errors.

Database size is 2.8 MB. Portainer config is simple:

```
version: "3.0"
services:
  tubesync:
    image: ghcr.io/meeb/tubesync:latest
    container_name: tubesync
    ports:
      - 4848:4848
    volumes:
      - /media/HDD/.containers/tubesync/config:/config
      - /media/NAS/Youtube/:/downloads
    environment:
      - TZ=America/Toronto
      - PUID=1000
      - PGID=1000
```

Not quite sure what changed but I never had this issue before :/ Strange.
