### ISSUE TITLE
database is locked

### ISSUE THREAD

**Issue by plsharevme** [meeb/tubesync#229]
hello, just install tubesync last night , and paste some source to download the video, 1st it run very well but after that it seem just stop, i have execute command reset the task from the command line, it continue to download few more task and stop again, after a day, i just retype reset task `docker exec -ti tubesync python3 /app/manage.py reset-tasks`

At task tab it show 
```
1 Running
Running tasks are tasks which currently being worked on right now.

Index media from source "Great Journey Of Teenagers 2"
Task started at 2022-04-07 09:16:16
0 Errors
```

i clicked inside VIEW TASKS LINKED TO THIS SOURCE 

now it show 
```
Source: "d1b28683-6d66-435b-950a-68ac086d21b4"
Error: "database is locked"
```
The task is no running or already hang i think.

Should i  need to restart my tubesync container(portainer stack) before execute the command? or any way to prevent database is locked ?
Thanks regard.

**Comment by meeb** [comment]
If you're running into database write lock issues I'd suggest trying a different database backend like Postgres:

https://github.com/meeb/tubesync/blob/main/docs/other-database-backends.md

**Comment by plsharevme** [comment]
> If you're running into database write lock issues I'd suggest trying a different database backend like Postgres:
> 
> https://github.com/meeb/tubesync/blob/main/docs/other-database-backends.md

hello, can you help me looks this stack is enough or correct ?
```
version: "3.7"
services:
  tubesync:
    image: ghcr.io/meeb/tubesync:latest
    container_name: tubesync
    restart: unless-stopped
    networks:
      - default
    ports:
      - 4848:4848
    volumes:
      - /srv/dev-disk-by-uuid-07a04a45-40a9-4876-a086-7cf85beb3688/data/setting/tubesync:/config
      - /srv/dev-disk-by-uuid-07a04a45-40a9-4876-a086-7cf85beb3688/data/youtube_downloads:/downloads
    environment:
      - TZ=Asia/Kuala_Lumpur
      - PUID=1000
      - PGID=100
      - UMASK=022
      - POSTGRES_USER=tubeuser
      - POSTGRES_PASSWORD=tubepassword
      - POSTGRES_DB=tubedb


  db:
    environment:
      POSTGRES_USER: tubeuser
      POSTGRES_PASSWORD: tubepassword
      POSTGRES_DB: tubedb
    image: postgres:latest
    networks:
      - default
    ports:
      - 5405:5432
    restart: always
    volumes:
      - /srv/dev-disk-by-uuid-07a04a45-40a9-4876-a086-7cf85beb3688/data/setting/postgresql:/var/lib/postgresql/data
```

**Comment by meeb** [comment]
It is not. TubeSync uses a connection string not connection parameters. Remove `POSTGRES_USER`, `POSTGRES_PASSWORD` and `POSTGRES_DB` from the `tubesync` service definition and add in:

`- DATABASE_CONNECTION=postgresql://tubeuser:tubepassword@db:5432/tubedb`

or whatever names for host and db etc. you're using. This is detailed in https://github.com/meeb/tubesync/blob/main/docs/other-database-backends.md quite well but it can be a bit confusing if you've not used connection strings before.

The `db` service looks fine.

**Comment by meeb** [comment]
Also TubeSync will write out what database it's connecting to when you start the container, so you can just restart it and check the container logs to confirm it's connecting to the right database as well.

**Comment by plsharevme** [comment]
```
version: "3.7"
services:
  tubesync:
    image: ghcr.io/meeb/tubesync:latest
    container_name: tubesync
    restart: unless-stopped
    networks:
      - default
    ports:
      - 4848:4848
    volumes:
      - /srv/dev-disk-by-uuid-07a04a45-40a9-4876-a086-7cf85beb3688/data/setting/tubesync:/config
      - /srv/dev-disk-by-uuid-07a04a45-40a9-4876-a086-7cf85beb3688/data/youtube_downloads:/downloads
    environment:
      - TZ=Asia/Kuala_Lumpur
      - PUID=1000
      - PGID=100
      - UMASK=022
      - DATABASE_CONNECTION=postgresql://tubeuser:tubepassword@db:5432/tubedb


  db:
    environment:
     POSTGRES_USER: tubeuser
     POSTGRES_PASSWORD: tubepassword
     POSTGRES_DB: tubedb
    image: postgres:latest
    user: 1000:100
    networks:
      - default
    ports:
      - 5432:5432
    restart: always
    volumes:
      - /srv/dev-disk-by-uuid-07a04a45-40a9-4876-a086-7cf85beb3688/data/setting/postgresql:/var/lib/postgresql/data
```

log of postgres

2022-04-07 13:49:57.186 UTC [223] FATAL:  database "tubedb" does not exist
2022-04-07 13:50:02.210 UTC [224] FATAL:  database "tubedb" does not exist

log of tubesync

Failed to retrieve tasks. Database unreachable.

## but i dun know which part of the docker-compose stack is wrong......can you point me?
