### ISSUE TITLE
HowTo request: tubesync with nginx reverse proxy (no SWAG, nor any other extras)

### ISSUE THREAD

**Issue by alneven** [meeb/tubesync#343]
hi there,
I checked all the entries here and elsewhere to have a working www.domain.com/**tubesync** URL (as for /radarr or /sonarr or bazarr or plex and transmission - everything is working) but somehow nothing fixed my problem.

I have checked the container itself (nginx or gunicorn), tried to disable ssl on my nginx config (not in the container), added the DJANGO URL PREFIX, HOST, PORT to docker-compse --- no success on any

I have always
404 - Page Not Found
The resource you have requested does not exist.

Any suggestion, working config would be great.

Of course I can access the IP:port if I portforward on my machine with ssh, and everything is working
But I would like to access the website from my phone, or another web browser without to connect via ssh

Thanks!

PS: I have no SWAG, just a normal nginx install and the tubesync docker

**Comment by meeb** [comment]
If you want to put tubesync behind another reverse proxy probably the easiest way is to bypass nginx in tubesync. Set the env vars `LISTEN_HOST` and `LISTEN_PORT` to something like `0.0.0.0` and `12345` or any port you like, then set `DJANGO_URL_PREFIX` to `/tubesync`. Finally, try pointing your upstream reverse proxy at `whatever.host:12345`.

The issue you're encountering is caused by two issues, first is you're putting nginx in front of another nginx instance, and Django (which tubesync uses as the framework) requires a tweak to work in a subdirectory.

If you do get it working please document what you did in this issue as it may be of use to others. Alternatively, you can drop a shell into the tubesync container and edit the nginx config directly in `/etc/nginx/nginx.conf`. If you make any edits that work for you document them here as well!

**Comment by alneven** [comment]
Thanks for the input, I played with it a bit and came to the following solution:

docker compose for tubesync:
```
  tubesync:
    image: "ghcr.io/meeb/tubesync:latest"
    container_name: tubesync
    restart: unless-stopped
    ports:
      - 4848:4848
    volumes:
      - ${USERDIR}/docker/tubesync/tubesync-config:/config
      - ${USERDIR}/docker/tubesync/tubesync-downloads:/downloads
    environment:
      - TZ=${TZ}
      - PUID=1000
      - PGID=1000
      - DJANGO_URL_PREFIX=/tubesync/
```


nginx config on the host server:
```
# Tubesync
 location /tubesync {
    auth_basic "off";
    allow all;
    proxy_pass http://127.0.0.1:4848;
    proxy_redirect  http://  $scheme://;
    proxy_set_header Connection $connection_upgrade;
    proxy_set_header Host $host;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-Proto http;
    proxy_set_header X-Real-IP $remote_addr;
  }
```

nginx in the container:
didn't changed it


to sum up:
I only had to add the DJANGO_URL_PREFIX (not the HOST and PORT!) in the docker compose AND change nginx redirect scheme.
In nginx I have also disabled the basic http auth what I have, but later on I will add it back that the "site" is not open for the internet and for everyone.
