### ISSUE TITLE
Memory usage during db migration

### ISSUE THREAD

**Issue by eeveelution1313** [meeb/tubesync#491]
I'm in the middle of migrating from sqlite to mariadb, in hopes of speeding some things up, and i'm seeing extremely high memory utilisation. I'm not sure if it could be related to it not being done with scheduled tasks before trying to switch. 

![image](https://github.com/meeb/tubesync/assets/32376193/4214496a-5c4f-4b26-b007-d0e0b2ac888b)

screenshot of stats before start of migration 
![IMG_4712](https://github.com/meeb/tubesync/assets/32376193/9f02822b-5c1b-4b4d-be92-52b1487bded2)

i followed the guide from here https://github.com/meeb/tubesync/blob/main/docs/other-database-backends.md

Not sure if it matters but it's running using podman-compose with the following
```yaml
  TubeSync:
    image: ghcr.io/meeb/tubesync:latest
    container_name: TubeSync
    ports:
      - 4848:4848
    volumes:
      - ./Managers/TubeSync:/config
      - /mnt/HDD/Media/Youtube/:/downloads
    environment:
      - TZ=Europe/Copenhagen
      - PUID=1000
      - PGID=1907200513
      - TUBESYNC_WORKERS=1
      - DATABASE_CONNECTION=mysql://user:pass@ip:3306/tubesync
    restart: unless-stopped
```

Very new to github, sorry if i didn't include something needed
