### ISSUE TITLE
Web page not loading

### ISSUE THREAD

**Issue by mikeyounge** [meeb/tubesync#552]
I'm having a weird issue where everything is working in the backend (media is downloaded, pings ok, shows pages have loaded in the logs), but nothing is loading on the browser, just a blank page. I have cleared my cookies, loaded it in an anonymous browser, tried different networks on different devices and nothing is loaded. I have deleted the container and recreated it. I have navigated through my reverse proxy and my local port and that nothing seems to make a difference.

Attached are my logs from the last reboot and attempt at loading the page.
[_tubesync_logs.txt](https://github.com/user-attachments/files/17689304/_tubesync_logs.txt)
Is there anything I can try to have it come back? I'm using a postgres db and the "latest" tag in docker.

This is my docker compose if that makes a difference as well.

```
#version: "3.7"

networks:
  default:
    external: true
    name: cloudnet
    
services:
  tubesync:
    image: ghcr.io/meeb/tubesync:latest
    labels:
      - "diun.enable=true"
      - "diun.metadata.ctn_names"
    container_name: tubesync
    depends_on:
      - tubesyncdb
    deploy:
      resources:
        limits:
          memory: 10GB
    restart: unless-stopped
    ports:
      - 4848:4848
    volumes:
      - /opt/tubesync/tubesync:/config
      - /mnt/storage/Videos/tubesync:/downloads
    environment:
      - TZ=America/Denver
      - PUID=13015
      - PGID=13000
      - UMASK=002
      - TUBESYNC_RESET_DOWNLOAD_DIR=False
      - GUNICORN_WORKERS=3
      - TUBESYNC_WORKERS=1
      - DATABASE_CONNECTION=postgresql://tubeuser:tubepassword@tubesyncdb:5432/tubedb
      - DJANGO_URL_PREFIX=/tubesync/

    dns:
      - 172.19.0.100


  tubesyncdb:
    container_name: tubesyncdb
    environment:
     - POSTGRES_USER=tubeuser
     - POSTGRES_PASSWORD=tubepassword
     - POSTGRES_DB=tubedb
    image: postgres:15
    labels:
      - "diun.enable=true"
      - "diun.metadata.ctn_names"
    user: 1000:1000
    ports:
      - 5432:5432
    restart: always
    volumes:
      - /opt/tubesync/postgresql:/var/lib/postgresql/data:rw
```

A quick glance at the web inspector of Chrome shows that the tubesync.css file is either missing or not loading. There is only an "(index)" file shown in the sources.

Any help would be appreciated. I'm glad it is still running in the background, but I do check in fairly frequently. This problem arose randomly in the last week. I don't know if it was related to any changes made to the code or my configuration.
