### ISSUE TITLE
Cant load, constant 502 errors/container restarts

### ISSUE THREAD

**Issue by jonatino** [meeb/tubesync#748]
![Image](https://github.com/user-attachments/assets/9f3a1ab0-d1ee-465f-84b4-a69a81d24d43)

Get 502 error every time, only 5 sources with ~3000 video files.

**Comment by jonatino** [comment]
I have 32gb of ram and system only shows 5% memory consumption, not sure why it's running out. 

docker compose:
```
services:
  tubesync:
    image: ghcr.io/meeb/tubesync:latest
    container_name: tubesync
    restart: unless-stopped
    ports:
      - 4848:4848
    volumes:
      - /volume1/docker/tubesync/config:/config
      - /volume1/media/other/tubesync:/downloads
    environment:
      - TZ=America/New_York
      - PUID=1027
      - PGID=100
      - TUBESYNC_RESET_DOWNLOAD_DIR=False
      - TUBESYNC_DEBUG=True
```
