### ISSUE TITLE
Failed to retrieve tasks. Database unreachable.

### ISSUE THREAD

**Issue by waxill** [meeb/tubesync#943]
I noticed that nothing had been downloading recently so after trying to manually skip and unskip some videos I noticed these errors popping up on the logs.
Failed to retrieve tasks. Database unreachable.
Failed to retrieve tasks. Database unreachable.
Failed to retrieve tasks. Database unreachable.
Failed to retrieve tasks. Database unreachable.
Failed to retrieve tasks. Database unreachable.
Failed to retrieve tasks. Database unreachable.
Failed to retrieve tasks. Database unreachable.
Failed to retrieve tasks. Database unreachable.
Failed to retrieve tasks. Database unreachable.
Failed to retrieve tasks. Database unreachable.
Failed to retrieve tasks. Database unreachable.
Failed to retrieve tasks. Database unreachable.
Failed to retrieve tasks. Database unreachable.

**Comment by tcely** [comment]
You can transition away from SQLite to a database with better support for concurrent access.

https://github.com/meeb/tubesync/issues/748#issuecomment-2673133029

Otherwise, waiting until the tasks are completed will likely result in those messages going away.

**Comment by Nanganator** [comment]
I’ve been having similar issues and am starting to think that I’ll need to do the migration to MariaDB as well.

I had this issue previously where my sqlite db had ballooned to over 5GB. I completely wiped my TubeSync setup and started fresh, and after adding all the channels back in and a full indexing and download the db was 32MB. It’s been a couple months and again the db has ballooned to 2.5GB and I’m beginning to get this issue again.

For me the db growth of the sqlite db seems unreasonable. I only ever monitor 10 sources. These sources have been operating for many years and have several hundred videos each. So after a full indexing there are perhaps 4000 videos indexed. However this only results in an sqlite db of 32MB.
But after 2 months and perhaps an additional 200 videos indexed, downloaded and then deleted (using the tubesync auto delete) the db had grown to 2.5GB! With the average release schedule of the 10 channels I monitor, and my “delete media older than” setting, I only ever have roughly 50 videos downloaded at any time.

My guess is that for every video downloaded, a considerable amount of additional information (vs just indexed) is added to the DB. However after the “delete media older than” period, that additional data is never flushed from the db despite no longer being needed, so the DB will continue this rapid trajectory of growth.

**Comment by tcely** [comment]
FYI, I have my main container and a testing container using PostgreSQL and this is the current storage being used:

`913M    /var/lib/postgresql/data`

**Comment by Nanganator** [comment]
If tubesync loads and you’re using sqlite it should just be written at the bottom of the dashboard page in the “Runtime information” section beside “Database”.

If tubesync doesn’t load (due to afformention database error) then you’d need to check the size of the db.sqlite3 file in the location where you mounted the config data for the tubesync container.
e.g.
```
volumes:
  - /some/directory/tubesync-config:/config
```

**Comment by waxill** [comment]
Database | sqlite at "/config/db.sqlite3" (1.7 GiB)

So not that large really?

Is there a way to purge it?

**Comment by tcely** [comment]
> Is there a way to purge it?

No. Deleting or removing metadata only results in new rows and tasks to fill it in again.

https://github.com/meeb/tubesync/blob/656ade6dd9f84d4a0decd4210f9d5b4d33083890/tubesync/tubesync/local_settings.py.container#L95-L100

There is a filter function to store less metadata per media instance available.

You can select if you want it to be applied only to newly retrieved metadata, or any time metadata is loaded from the database. The latter changes every media instance in your database eventually.

**Comment by tcely** [comment]
@waxill Please pull the latest image and let us know if you still see any issues. Thanks!

**Comment by waxill** [comment]
Ok I will try to do a pull.
In the meantime I did try to add postgres database using the guide in the link you posted. I use docker compose so I created the following new file.
`tubesync-db:
  image: postgres:15.2
  container_name: tubesync-db
  restart: unless-stopped
  volumes:
      - /usr/local/etc/tubesync-init/init.sql:/docker-entrypoint-initdb.d/init.sql
      - /usr/local/etc/tubesync-db:/var/lib/postgresql/data
  environment:
   - POSTGRES_USER=postgres
   - POSTGRES_PASSWORD=apassword

 tubesync:
  image: ghcr.io/meeb/tubesync:latest
  container_name: tubesync
  restart: unless-stopped
  ports:
   - 4848:4848
  volumes:
      - /usr/local/etc/tubesync-config:/config
      - /media/series2/tubesync-downloads:/downloads
  environment:
   - DATABASE_CONNECTION=postgresql://postgres:apassword@tubesync-db:5432/tubesync
  depends_on:
   - tubesync-db`

I also added the init.sql line as instructed.
but it didnt seem to start and I saw the following in the logs;

`docker logs tubesync -f
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service tubesync-init: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
TUBESYNC_RESET_DOWNLOAD_DIR=True, Resetting /downloads directory permissions
Using database connection: postgresql://postgres:[hidden]@tubesync-db:5432/tubesync
Traceback (most recent call last):
  File "/app/manage.py", line 18, in <module>
    main()
  File "/app/manage.py", line 14, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.11/dist-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.11/dist-packages/django/core/management/__init__.py", line 416, in execute
    django.setup()
  File "/usr/local/lib/python3.11/dist-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.11/dist-packages/django/apps/registry.py", line 116, in populate
    app_config.import_models()
  File "/usr/local/lib/python3.11/dist-packages/django/apps/config.py", line 269, in import_models
    self.models_module = import_module(models_module_name)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/sync/models.py", line 23, in <module>
    from .youtube import (get_media_info as get_youtube_media_info,
  File "/app/sync/youtube.py", line 36, in <module>
    (_youtubedl_tempdir_path / '.ignore').touch(exist_ok=True)
  File "/usr/lib/python3.11/pathlib.py", line 1109, in touch
    fd = os.open(self, flags, mode)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/downloads/cache/.ignore'`

**Comment by tcely** [comment]
That `PermissionError` points to problems creating the `/downloads/cache/.ignore` file.

What does `/media/series2/tubesync-downloads` allow?

Is there a `cache` directory present?

**Comment by Nanganator** [comment]
Also, if `/media/series2/tubesync-downloads` on your host is an SMB/CIFS share you are mounting, make sure to add :shared to the end of the volume in your compose file. It solves a LOT of issues with permissions on SMB.

`/media/series2/tubesync-downloads:/downloads:shared`

**Comment by waxill** [comment]
> That `PermissionError` points to problems creating the `/downloads/cache/.ignore` file.
> 
> What does `/media/series2/tubesync-downloads` allow?
> 
> Is there a `cache` directory present?

```
test@fred:/media/series2/tubesync-downloads$ l
total 8.0K
drwxr-xr-x 2 test root    0 Dec 28 09:02 .
drwxr-xr-x 2 test root    0 Aug 22  2023 ..
drwxr-xr-x 2 test root    0 Apr 14 05:27 cache
-rwxr-xr-x 1 test root 7.2K Nov 25  2023 utils.py
drwxr-xr-x 2 test root    0 Apr 14 11:18 video
test@fred:/media/series2/tubesync-downloads$ cd cache
test@fred:/media/series2/tubesync-downloads/cache$ l
total 0
drwxr-xr-x 2 test root 0 Apr 14 05:27 .
drwxr-xr-x 2 test root 0 Dec 28 09:02 ..
-rwxr-xr-x 1 test root 0 Apr 14 10:38 .ignore
drwxr-xr-x 2 test root 0 Apr  7 16:55 .yt_dlp-RYasobEx34w-wc9iy1rr
```

**Comment by tcely** [comment]
What does your original compose file look like?

You probably need to match your user to the mount.
See the note at the end of the installation section 
https://github.com/meeb/tubesync#installation

**Comment by waxill** [comment]
> What does your original compose file look like?
> 
> You probably need to match your user to the mount. See the note at the end of the installation section https://github.com/meeb/tubesync#installation

```
  tubesync:
    image: ghcr.io/meeb/tubesync:latest
    container_name: tubesync
    restart: unless-stopped
    ports:
      - 4848:4848
    volumes:
      - /usr/local/etc/tubesync-config:/config
      - /media/series2/tubesync-downloads:/downloads:shared
    environment:
      - TZ=Europe/London
      - PUID=1000
      - PGID=1000
   ```
I have reverted back to this for now

**Comment by tcely** [comment]
That explains it.

Your new compose file didn't have the user/group ID:
```
      - PUID=1000
      - PGID=1000
```

**Comment by waxill** [comment]
How does this look now?
```
 tubesync-db:
  image: postgres:15.2
  container_name: tubesync-db
  restart: unless-stopped
  volumes:
      - /usr/local/etc/tubesync-init/init.sql:/docker-entrypoint-initdb.d/init.sql
      - /usr/local/etc/tubesync-db:/var/lib/postgresql/data
  environment:
   - POSTGRES_USER=postgres
   - POSTGRES_PASSWORD=apassword

 tubesync:
  image: ghcr.io/meeb/tubesync:latest
  container_name: tubesync
  restart: unless-stopped
  ports:
   - 4848:4848
  volumes:
      - /usr/local/etc/tubesync-config:/config
      - /media/series2/tubesync-downloads:/downloads:shared
  environment:
   - DATABASE_CONNECTION=postgresql://postgres:apassword@tubesync-db:5432/tubesync
   - TZ=Europe/London
   - PUID=1000
   - PGID=1000
  depends_on:
   - tubesync-db
```
Or do I also need to add PUID and PGID to the environment section for the postgres image?
