### ISSUE TITLE
Dev Build Errors

### ISSUE THREAD

**Issue by RichardHyde** [meeb/tubesync#964]
I'm struggling to setup a build environment for v0.14.1. I first hit errors as the `Pipfile.lock` isn't included so I've installed the python modules individually using pip, but I'm getting an error importing `yt_dlp.patch` which I can't find anywhere.

My GitHub fork of Tubesync is also failing to build in the `containerise` action with a `dive` error

```
Results:
  FAIL: highestUserWastedPercent: too many bytes wasted, relative to the user bytes added (%-user-wasted-bytes=0.04098538717992909 > threshold=0.03)
  FAIL: highestWastedBytes: too many bytes wasted (wasted-bytes=20590428 > threshold=10000000)
  PASS: lowestEfficiency
Result:FAIL [Total:3] [Passed:1] [Failed:2] [Warn:0] [Skipped:0]
```

Any hints of getting a working dev environment working?
